language: rust

cache:
  directories:
    - /home/travis/.cargo

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly
      script: cargo test
    - rust: beta
      script: cargo check --manifest-path examples/wasm/Cargo.toml
    - rust: stable
      script: cargo check --manifest-path examples/wasm/Cargo.toml
